spring.application.name=tdspring
spring.datasource.url=jdbc:mariadb://localhost:3306/${MYSQL_DATABASE}
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
pdf.storage.path=/var/www/OPtiBox/SHOP-STI_Back/spring-app/PDFCheck
start-class=com.example.tdspring.TdspringApplication
server.port=8000
